### ISSUE TITLE
报错！

### ISSUE THREAD

**Issue by gzxiexl** [Syuvii/EldenRingFastSave#1]
先说明下我的使用场景 我在家里电脑A和单位宿舍电脑B通过syncthing把C:\Users\gzxie\Documents\EldenRingBackFile文件夹同步。
再电脑A快速存档后的文件顺利同步到了电脑B，但是电脑B上运行快速换挡 出现问题，求解决
![微信截图_20220314155850](https://user-images.githubusercontent.com/40417977/158129614-4a0693cf-d109-49fe-8c3c-f8788a23db50.png)

**Comment by gzxiexl** [comment]
GraphicsConfig.xml 看起来是图形设置config文件，其实进度只需要保存ER0000.sl2和ER0000.sl2.bak 两个文件就可以 会不会是上级目录名 每串数字都不一样导致的呢？

**Comment by Syuvii** [comment]
@gzxiexl  能看下你的C:\Users\AppData\Roaming\EldenRing下的目录结构吗

**Comment by Syuvii** [comment]
这也是前几天随便写给自己用的

**Comment by gzxiexl** [comment]
![image](https://user-images.githubusercontent.com/40417977/158131187-73fb9be4-ac62-4e6d-9510-87727a9ade80.png)

**Comment by gzxiexl** [comment]
![image](https://user-images.githubusercontent.com/40417977/158131333-b7494c33-c7e5-4a88-b978-d45461875152.png)

**Comment by gzxiexl** [comment]
GraphicsConfig.xml是图形设置 不必同步的 
ER0000.sl2和ER0000.sl2.bak 两个备份就可以了

**Comment by Syuvii** [comment]
可是按道理不是这个的问题啊，这个的作用就是代替了手动压缩解压

**Comment by Syuvii** [comment]
那你输入1试试（解压第一个）

**Comment by Syuvii** [comment]
你在A电脑上能正常使用吗

**Comment by gzxiexl** [comment]
输入1也是无此存档

**Comment by Syuvii** [comment]
![image](https://user-images.githubusercontent.com/74316230/158132688-abdb691d-eb27-4421-a31e-78b3820d67f8.png)

**Comment by Syuvii** [comment]
你试试直接运行main.py这个文件？

**Comment by gzxiexl** [comment]
直接运行要安装python吧

**Comment by Syuvii** [comment]
我觉得打包出错的可能性很小，推测一下几个可能：
1. 只有输入的数字不在 1至 存档数+1 这个范围内才会触发无此存档，推测可能输入问题
2. 未知bug

**Comment by Syuvii** [comment]
如果按0不能退出那就是输入问题了

**Comment by TrymenT-AlphA** [comment]
游戏退回标题界面了吗

**Comment by TrymenT-AlphA** [comment]
@gzxiexl 游戏退回标题界面了吗

**Comment by gzxiexl** [comment]
![image](https://user-images.githubusercontent.com/40417977/158140926-4f93b181-96de-45f3-a90c-3b06b280d251.png)
按0推出无问题

**Comment by gzxiexl** [comment]
晚上回家了我截图发上来

**Comment by gzxiexl** [comment]
> 我想看看B电脑的C:\Users\Documents\EldenRingBackFile下的目录，这属实有点诡异（）

B电脑的这个目录 跟A电脑的一模一样 因为syncthing设置了双向同步
![image](https://user-images.githubusercontent.com/40417977/158164315-ad4480f4-d085-4877-9b70-2576febcad7f.png)

**Comment by Syuvii** [comment]
删除.stfolder和EldenRingFastSave.exe，这个目录下只能有zip文件

**Comment by gzxiexl** [comment]
.stfolder是syncthing建立的 ，删除了我就没法2台电脑双向备份啦，有解决办法吗？

**Comment by Syuvii** [comment]
有，但我还没写，之后写吧（）

**Comment by gzxiexl** [comment]
期待，感谢大佬造福游戏迷

**Comment by Syuvii** [comment]
@gzxiexl 反馈问题已修复，可以查看v0.1版本

**Comment by gzxiexl** [comment]
新版非常好用 谢谢大佬

**Comment by Syuvii** [comment]
这个功能也就这样了（已经想不出来新花样哩）
